import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import "cal-sans";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  weight: ["500"],
});

export const metadata: Metadata = {
  title: "ECOFARM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
