import type { Metadata } from "next";
import "./globals.css";
import LandingNav from "@/components/common/navbars/LandingNav";
import {Montserrat} from "next/font/google"

const montserrat = Montserrat ({
  subsets: ["latin"],
  display:"swap",
});

export const metadata: Metadata = {
  title: "ECOFARM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <LandingNav />
        <main>{children}</main>
      </body>
    </html>
  );
}
